dist: trusty

language: php

before_script:
  - composer install --ignore-platform-reqs
  # - npm install # No need right now as we are not running any JS tests
  # - npm run build # No need right now as we are not running any JS tests

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.npm
    - node_modules
    - $HOME/vendor

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - develop
    - main

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
