sudo: true
dist: trusty

language: php

before_script:
  - composer install --ignore-platform-reqs
  - npm install
  - npm run build

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.npm
    - node_modules
    - $HOME/vendor

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - develop
    - main

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=latest
